language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install -e ."
  - "pip install -r requirements.txt"
  - "pip install -r dev_requirements.txt"
  - "apt-get install npm"
  - "npm install -g casperjs"
# command to run tests
script: coverage run --source=dataportal_test_runner setup.py nosetests
after_success: coveralls
